List<String> svglist = [
  "asset/svg_emoji/emo_5.svg",
  "asset/svg_emoji/emo_2.svg",
  "asset/svg_emoji/emo_5.svg",
  "asset/svg_emoji/emo_8.svg",
  "asset/svg_emoji/emo_2.svg",
  "asset/svg_emoji/emo_4.svg",
  "asset/svg_emoji/emo_8.svg",
  "asset/svg_emoji/emo_1.svg",
  "asset/svg_emoji/emo_3.svg",
  "asset/svg_emoji/emo_6.svg",
  "asset/svg_emoji/emo_7.svg",
  "asset/svg_emoji/emo_3.svg",
  "asset/svg_emoji/emo_7.svg",
  "asset/svg_emoji/emo_1.svg",
  "asset/svg_emoji/emo_4.svg",
  "asset/svg_emoji/emo_6.svg",
];

List<String> imglist = [
  "asset/img/emo_5.jpg",
  "asset/img/emo_2.jpg",
  "asset/img/emo_5.jpg",
  "asset/img/emo_8.jpg",
  "asset/img/emo_2.jpg",
  "asset/img/emo_4.jpg",
  "asset/img/emo_8.jpg",
  "asset/img/emo_1.jpg",
  "asset/img/emo_3.jpg",
  "asset/img/emo_6.jpg",
  "asset/img/emo_7.jpg",
  "asset/img/emo_3.jpg",
  "asset/img/emo_7.jpg",
  "asset/img/emo_1.jpg",
  "asset/img/emo_4.jpg",
  "asset/img/emo_6.jpg",
];

List<String> pnglist = [
  "asset/png/emo_1.png",
  "asset/png/emo_2.png",
  "asset/png/emo_8.png",
  "asset/png/emo_4.png",
  "asset/png/emo_2.png",
  "asset/png/emo_1.png",
  "asset/png/emo_7.png",
  "asset/png/emo_3.png",
  "asset/png/emo_6.png",
  "asset/png/emo_3.png",
  "asset/png/emo_4.png",
  "asset/png/emo_8.png",
  "asset/png/emo_5.png",
  "asset/png/emo_6.png",
  "asset/png/emo_7.png",
  "asset/png/emo_5.png",
];

List<bool> boollist = [
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];